app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

customs:
    resource: "@AppBundle/Controller/IndexController.php"
    type:     annotation